In [20]:
names = ['Ben', 'Omer', 'Karen', 'Celine', 'Sue', 'Bora', 'Rose', 'Ellen', 'Bob', 'Taylor', 'Jude']
call_numbers = [300, 10, 500, 70, 100, 100, 600, 800, 200, 450, 80]
average_deal_sizes = [8, 6, 24, 32, 5, 25, 25, 40, 15, 10, 12]
revenues = [2400, 60, 12000, 2275, 500, 770, 4000, 6000, 800, 1200, 500]

In [12]:
import numpy as np

In [13]:
data = np.array([], dtype=int)

In [26]:
def append_names(names_list):
  global data
  for i in names_list:
    data = np.append(data, names.index(i))

In [17]:
def append_performance_measures(feature_list):
  global data
  data = np.append(data, feature_list)

In [27]:
append_names(names)
append_performance_measures(call_numbers)
append_performance_measures(average_deal_sizes)
append_performance_measures(revenues)

print(data)
print(data.shape)

[    0     1     2     3     4     5     6     7     8     9    10   300
    10   500    70   100   100   600   800   200   450    80     8     6
    24    32     5    25    25    40    15    10    12  2400    60 12000
  2275   500   770  4000  6000   800  1200   500]
(44,)


In [29]:
data = data.reshape(4, 11)
print(data)
print(data.shape)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]]
(4, 11)


In [30]:
print(data[1])

[300  10 500  70 100 100 600 800 200 450  80]


In [31]:
print(data[2])

[ 8  6 24 32  5 25 25 40 15 10 12]


In [32]:
print(data[3])

[ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]


In [33]:
print(data[3,7])

6000


In [34]:
def calculate_performance(employee_name):
  idx = names.index(employee_name)
  number_of_calls = data[1, idx]
  avg_deal_size = data[2,idx]
  revenue = data[3, idx]

  score = (avg_deal_size*revenue) / number_of_calls

  return score

In [35]:
print(calculate_performance("Ellen"))

300.0


In [36]:
performance_scores = []
for name in names:
  score = int(calculate_performance(name))
  performance_scores.append(score)

In [37]:
data = np.concatenate((data, [performance_scores]), axis = 0)
print(data)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]
 [   64    36   576  1040    25   192   166   300    60    26    75]]


In [39]:
idx_best_employee = np.argmax(data[4])
idx_worst_employee = np.argmin(data[4])

print(f'Best Performing Employee: {names[idx_best_employee]}')
print(f'Worst Performing Employee: {names[idx_worst_employee]}')

Best Performing Employee: Celine
Worst Performing Employee: Sue
